#!/usr/bin/env bash

set -e

echo -e "\033[0;1m› configure and link dotfiles\033[0m"
source script/link

echo -e "\033[0;1m› create directories in home\033[0m"
mkdir -p ~/code ~/documents ~/downloads ~/movies ~/music ~/pictures ~/public

echo -e "\033[0;1m› system update\033[0m"
sudo apt-get update
sudo apt-get upgrade

echo -e "\033[0;1m› install essentials\033[0m"
sudo apt-get install -y \
  build-essential \
  curl \
  git \
  python-setuptools

echo -e "\033[0;1m› install software\033[0m"
source script/install

echo -e "\033[0;1m› change shell\033[0m"
sudo apt-get install -y zsh
chsh -s $(which zsh)

echo -e "\033[0;1m› reboot when ready\033[0m"
