#!/usr/bin/env bash

set -e

echo "› configure and link dotfiles"
source script/link > /tmp/dotfiles-link.log 2>&1

echo "› system update"
sudo apt-get update
sudo apt-get upgrade

echo "› install essentials"
sudo apt-get install -y \
  build-essential \
  curl \
  git \
  python-setuptools \
  ruby

echo "› install linuxbrew"
source linuxbrew/install.sh > /tmp/linuxbrew-install.log 2>&1

echo "› install software"
source script/install > /tmp/dofiles-install.log 2>&1

echo "› change shell"
sudo apt-get install -y zsh
chsh -s $(which zsh)

echo "› reboot"
sudo reboot
