#!/usr/bin/env bash

set -e

cd "$(dirname $0)"/..

# install apt packages
pkgs=$(cat aptfile | grep -o "^[^#]*" | tr -s "\n" " " | sed -e "s/[[:space:]]*$//g")
sudo apt-get install -y $pkgs

# create local install directory
mkdir -p ~/local/{bin,etc,include,lib,man,sbin,share,src}

# run install scripts
find . -name install.sh | while read installer; do sh "${installer}"; done
