#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
ZSH=$(pwd -P)

info () {
  echo -e "\033[0;34m..\033[0m $1"
}

success () {
  echo -e "\033[0;32m++\033[0m $1"
}

user () {
  echo -e "\033[0;33m??\033[0m $1"
}

link () {
  local src=$1 dst=$2

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then
    success "skipped $src"
  else
    ln -s "$src" "$dst"
    success "linked $src -> $dst"
  fi
}

linkall () {
  for src in $(find -H "$ZSH" -maxdepth 2 -name '*.symlink' -not -path '*.git')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link "$src" "$dst"
  done
}

linkall
