#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
ZSH=$(pwd -P)

info () {
  echo -e "  \033[0;34m..\033[0m $1"
}

success () {
  echo -e "  \033[0;32m++\033[0m $1"
}

user () {
  echo -e "  \033[0;33m??\033[0m $1"
}

gitconfig () {
  if [ ! -f git/gitconfig.local.symlink ]
  then
    info "set up git config"

    user "what is your github name?"
    read -e githubname

    user "what is your github email?"
    read -e githubmail

    sed \
      -e "s/AUTHORNAME/$githubname/g" \
      -e "s/AUTHOREMAIL/$githubmail/g" \
      git/gitconfig.local.symlink.template \
      > git/gitconfig.local.symlink

    success "git config"
  fi
}

link () {
  local src=$1 dst=$2

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then
    success "skipped $src"
  else
    ln -s "$src" "$dst"
    success "linked $src -> $dst"
  fi
}

linkall () {
  for src in $(find -H "$ZSH" -maxdepth 2 -name '*.symlink' -not -path '*.git')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link "$src" "$dst"
  done
}

gitconfig
linkall
